/**
 * Machine-readable error codes for API consumers.
 * These provide a stable contract for error handling on the client side.
 */
export enum ErrorCode {
  // 400 - Validation errors
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NO_FIELDS_TO_UPDATE = 'NO_FIELDS_TO_UPDATE',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  VALUE_BOOLEAN_REQUIRED = 'VALUE_BOOLEAN_REQUIRED',
  VALUE_NUMERIC_REQUIRED = 'VALUE_NUMERIC_REQUIRED',
  VALUE_DURATION_REQUIRED = 'VALUE_DURATION_REQUIRED',

  // 401 - Authentication errors
  NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // 403 - Authorization errors
  CANNOT_MODIFY_SYSTEM_DEFAULT = 'CANNOT_MODIFY_SYSTEM_DEFAULT',
  CANNOT_MODIFY_OTHER_USER = 'CANNOT_MODIFY_OTHER_USER',
  CANNOT_DELETE_SYSTEM_DEFAULT = 'CANNOT_DELETE_SYSTEM_DEFAULT',
  CANNOT_DELETE_OTHER_USER = 'CANNOT_DELETE_OTHER_USER',
  CANNOT_LOG_OTHER_USER = 'CANNOT_LOG_OTHER_USER',

  // 404 - Not found errors
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SYMPTOM_NOT_FOUND = 'SYMPTOM_NOT_FOUND',
  SYMPTOM_LOG_NOT_FOUND = 'SYMPTOM_LOG_NOT_FOUND',
  MOOD_LOG_NOT_FOUND = 'MOOD_LOG_NOT_FOUND',
  MEDICATION_NOT_FOUND = 'MEDICATION_NOT_FOUND',
  MEDICATION_LOG_NOT_FOUND = 'MEDICATION_LOG_NOT_FOUND',
  HABIT_NOT_FOUND = 'HABIT_NOT_FOUND',
  HABIT_LOG_NOT_FOUND = 'HABIT_LOG_NOT_FOUND',

  // 409 - Conflict errors
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  // 500 - Server errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
